package render

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/mparvin/awesome-stars/internal/github"
)

var anchorSanitizer = regexp.MustCompile(`[^a-z0-9\- ]`)

// RenderREADME generates an Awesome-style markdown README from star lists.
func RenderREADME(lists []github.List, cfg Config, updatedAt time.Time) string {
	lists = FilterLists(lists, cfg)

	var b strings.Builder

	title := cfg.ProjectTitle()
	fmt.Fprintf(&b, "# %s\n\n", title)
	b.WriteString("> Do not edit manually — generated by [awesome-stars](https://github.com/mparvin/awesome-stars).\n\n")
	b.WriteString(fmt.Sprintf("Last updated: %s\n\n", updatedAt.UTC().Format(time.RFC3339)))

	categories := make([]CategoryMeta, 0, len(lists))
	for _, list := range lists {
		categories = append(categories, ResolveCategory(list.Name, cfg))
	}
	SortCategories(categories)

	listByName := make(map[string]github.List, len(lists))
	for _, list := range lists {
		listByName[list.Name] = list
	}

	b.WriteString("## Table of Contents\n\n")
	for _, cat := range categories {
		fmt.Fprintf(&b, "- [%s](#%s)\n", cat.Title, cat.Anchor)
	}
	b.WriteString("\n")

	for _, cat := range categories {
		list := listByName[cat.ListName]
		repos := append([]github.Repository(nil), list.Repos...)
		sort.Slice(repos, func(i, j int) bool {
			return repos[i].StargazerCount > repos[j].StargazerCount
		})

		fmt.Fprintf(&b, "## %s\n\n", cat.Title)
		if len(repos) == 0 {
			b.WriteString("_No repositories in this list yet._\n\n")
			continue
		}

		for _, repo := range repos {
			line := fmt.Sprintf("- [%s](%s) ⭐ %s", repo.NameWithOwner, repo.URL, formatStars(repo.StargazerCount))
			desc := strings.TrimSpace(repo.Description)
			if desc != "" {
				line += " — " + desc
			}
			b.WriteString(line + "\n")
		}
		b.WriteString("\n")
	}

	return b.String()
}

func formatStars(count int) string {
	return fmt.Sprintf("%d", count)
}

func anchorID(title string) string {
	s := strings.ToLower(title)
	s = anchorSanitizer.ReplaceAllString(s, "")
	s = strings.Join(strings.Fields(s), "-")
	return s
}
